name: myconference
version: 0.0.1
description: A sample web application
dependencies:
  cookie: "^0.0.4"
  browser: any
  messenger: "^0.0.7"
  polymer: ">=0.15.1 <0.17.0"
  sqljocky: any
  test: "^0.12.5+1"
dev_dependencies:
  unittest: any